### ISSUE TITLE
Suggestion for makefile terminology

### ISSUE THREAD

**Issue by gzentner** [BrendelGroup/GoSTRIPES#18]
In the makefile, the TATAGGG sequence present in the 5' read is given the variable of "ADAPTER." I think this would more appropriately be called a "spacer" or "linker" (it's referred to as a linker in nanoCAGE - https://link.springer.com/protocol/10.1007%2F978-1-4939-6716-2_4), as the term "adapter" conventionally refers to the sequences appended to the molecule of interest to enable binding to the flow cell and sequencing primer association. In our case, this is everything but the UMI, barcode, and TATAGGG.

**Comment by vpbrendel** [comment]
The variable name was chosen because we use the cutadapt tool to remove the linker, as it were.
We also have the selectAdapterTrimmedReads.pl script.
Thus, there is a bit of both terms used. I think we should leave the tool names untouched, as they are generic tools. But we could change ADAPTER to LINKER throughout, with the understanding that the LINKER sequence is being processed like any old adapter sequence ...
Your choice.

**Comment by vpbrendel** [comment]
The current version uses the LINKER variable name.
